spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "viacheslawl@gmail.com"
    password: podlatfvvgeluasy
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  security:
    user:
      name: murdered
      password: murdered
  messages:
    basename: messages
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      pool-name: HikariCP-1
      auto-commit: true

  jpa:
    properties.hibernate:
      show_sql: false
      format_sql: true